#!/usr/bin/env python3
"""
Sync device definitions from upstream openrazer.

Usage:
  python scripts/sync_devices.py

Downloads the latest keyboards.py and mouse.py from the upstream openrazer
repo and writes adapted versions into service/hardware/, stripping out
Linux-specific imports (pyudev, dbus, EVENT_FILE_REGEX) while preserving
USB_PID, METHODS, HAS_MATRIX, MATRIX_DIMS, and DPI_MAX.

This lets you keep device support up-to-date by running one command whenever
upstream adds new hardware.
"""

import ast
import pathlib
import re
import sys
import textwrap
import urllib.request

UPSTREAM_BASE = "https://raw.githubusercontent.com/openrazer/openrazer/master/daemon/openrazer_daemon/hardware"
UPSTREAM_FILES = ["keyboards.py", "mouse.py"]

OUT_DIR = pathlib.Path(__file__).parent.parent / "service" / "hardware"

LINUX_IMPORTS = re.compile(
    r"^from openrazer_daemon.*$|^import .*pyudev.*$|^import .*dbus.*$",
    re.MULTILINE,
)
EVENT_FILE_REGEX = re.compile(r"^\s+EVENT_FILE_REGEX\s*=.*$\n", re.MULTILINE)
DEVICE_IMAGE = re.compile(r"^\s+DEVICE_IMAGE\s*=.*$\n", re.MULTILINE)

# Base-class rename map: upstream name → our local name
BASE_CLASS_MAP = {
    "RazerDeviceBrightnessSuspend": "RazerDevice",
    "_RazerDeviceBrightnessSuspend": "RazerDevice",
    "__RazerDeviceBrightnessSuspend": "RazerDevice",
    "RazerDevice": "RazerDevice",
    "__RazerDevice": "RazerDevice",
    "_RazerDevice": "RazerDevice",
    "_MacroKeyboard": "_Keyboard",
    "_RippleKeyboard": "_Keyboard",
}


def _fetch(url: str) -> str:
    with urllib.request.urlopen(url, timeout=15) as r:
        return r.read().decode()


def _adapt(source: str, filename: str) -> str:
    """Strip Linux-specific lines and rename base classes."""
    source = LINUX_IMPORTS.sub("", source)
    source = EVENT_FILE_REGEX.sub("", source)
    source = DEVICE_IMAGE.sub("", source)

    for old, new in BASE_CLASS_MAP.items():
        source = re.sub(rf"\b{re.escape(old)}\b", new, source)

    header = textwrap.dedent(f"""\
        # AUTO-GENERATED by scripts/sync_devices.py — do not edit manually.
        # Source: {UPSTREAM_BASE}/{filename}
        #
        # To update: python scripts/sync_devices.py

        from .device_base import RazerDevice

    """)

    # Remove leading blank lines / leftover stray imports
    body = re.sub(r"^\n+", "", source)
    return header + body


def main() -> None:
    for fname in UPSTREAM_FILES:
        url = f"{UPSTREAM_BASE}/{fname}"
        print(f"Fetching {url} ...", end=" ", flush=True)
        try:
            source = _fetch(url)
        except Exception as exc:
            print(f"FAILED: {exc}")
            sys.exit(1)

        adapted = _adapt(source, fname)
        out_path = OUT_DIR / fname
        out_path.write_text(adapted, encoding="utf-8")
        print(f"→ {out_path}")

    print("Done. Review the generated files for any remaining Linux-specific code.")


if __name__ == "__main__":
    main()
